version: '3'
services:
    # Database
    database-mysql:
        image: mysql:8.0
        container_name: database-mysql
        ports:
            - "3308:3306"
        env_file:
            - .env
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    # Backend Application
    backend-application:
        build: .
        container_name: backend-application
        env_file:
            - .env
        ports:
            - "5000:5000"
        environment:
            - PORT=5000
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - JWT_ACCESS_SIGNATURE=${JWT_ACCESS_SIGNATURE}
            - JWT_REFRESH_SIGNATURE=${JWT_REFRESH_SIGNATURE}
        depends_on:
            - database-mysql
