version: '3'
services:
    # Database
    database-postgres:
        image: postgres:14.2-alpine
        container_name: database-postgres
        ports:
            - "5432:5432"
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
    # Backend Application
    backend-application:
        build: .
        container_name: backend-application
        env_file:
            - .env
        ports:
            - "5000:5000"
        environment:
            - PORT=5000
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - JWT_ACCESS_SIGNATURE=${JWT_ACCESS_SIGNATURE}
            - JWT_REFRESH_SIGNATURE=${JWT_REFRESH_SIGNATURE}
        depends_on:
            - database-postgres
