version: '3'
services:
    # Database
    vearclthng-postgres:
        image: postgres:14.2-alpine
        container_name: vearclthng-postgres
        ports:
            - "5432:5432"
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB_NAME}
    # Web Server
    vearclthng-nginx:
        image: nginx:1.21-alpine
        container_name: vearclthng-nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - vearclthng
    # Backend Application
    vearclthng:
        image: ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}
        container_name: vearclthng
        env_file:
            - .env
        ports:
            - "5000:5000"
        environment:
            - PORT=5000
            - JWT_ACCESS_SIGNATURE=${JWT_ACCESS_SIGNATURE}
            - JWT_REFRESH_SIGNATURE=${JWT_REFRESH_SIGNATURE}
            - DATABASE_URL=${DATABASE_URL}
        depends_on:
            - vearclthng-postgres
