version: '3'
services:
    # Database
    vear-clthng-postgres:
        image: postgres:14-alpine
        container_name: vear-clthng-postgres
        ports:
            - "5432:5432"
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB_NAME}
    # Backend Application
    vear:
        image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:latest
        container_name: vear
        env_file:
            - .env
        ports:
            - "5000:5000"
        environment:
            - HOST=localhost
            - PORT=5000
            - JWT_ACCESS_SIGNATURE=${JWT_ACCESS_SIGNATURE}
            - JWT_REFRESH_SIGNATURE=${JWT_REFRESH_SIGNATURE}
            - DATABASE_URL=${DATABASE_URL}
        depends_on:
            - vear-clthng-postgres
    # Web Server
    vear-clthng-nginx:
        image: nginx:alpine
        container_name: vear-clthng-nginx
        ports:
            - "80:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - vear
