version: '3'
services:
    database-postgres:
        image: postgres:14-alpine
        ports:
            - "5432:5432"
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${POSTGRES_USERNAME}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB_NAME}
    apps-backend:
        image: ${DOCKER_USERNAME}/${DOCKER_REPOSITORY}:latest
        env_file:
            - .env
        ports:
            - "5000:5000"
        environment:
            - HOST=localhost
            - PORT=5000
            - JWT_ACCESS_SIGNATURE=${JWT_ACCESS_SIGNATURE}
            - JWT_REFRESH_SIGNATURE=${JWT_REFRESH_SIGNATURE}
            - DATABASE_URL=${DATABASE_URL}
        depends_on:
            - database-postgres
