export const AuthActionTypes = {
  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILED: 'SIGN_IN_FAILED',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILED: 'SIGN_UP_FAILED',
};

export const CartActionTypes = {
  ADD_ITEM_TO_CART_SUCCESS: 'ADD_ITEM_TO_CART_SUCCESS',
  ADD_ITEM_TO_CART_FAILED: 'ADD_ITEM_TO_CART_FAILED',
  REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
  UPDATE_CART_ITEM: 'UPDATE_CART_ITEM',
};

export const FavoActionTypes = {
  ADD_ITEM_TO_FAVO_SUCCESS: 'ADD_ITEM_TO_FAVO_SUCCESS',
  ADD_ITEM_TO_FAVO_FAILED: 'ADD_ITEM_TO_FAVO_FAILED',
  REMOVE_ITEM_FROM_FAVO: 'REMOVE_ITEM_FROM_FAVO',
  UPDATE_FAVO_ITEM: 'UPDATE_FAVO_ITEM',
};

export const ProductActionTypes = {
  FETCH_PRODUCT_START: 'FETCH_PRODUCT_START',
  FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
  FETCH_PRODUCT_FAILED: 'FETCH_PRODUCT_FAILED',
};
