export const DirectoryTypes = {
  FETCH_DIRECTORY_START: 'FETCH_DIRECTORY_START',
  FETCH_DIRECTORY_SUCCESS: 'FETCH_DIRECTORY_SUCCESS',
  FETCH_DIRECTORY_FAILED: 'FETCH_DIRECTORY_FAILED',
};

export const CollectionTypes = {
  FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
  FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
  FETCH_COLLECTION_FAILED: 'FETCH_COLLECTION_FAILED',
};
