export const AuthTypes = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
  SIGN_IN_START: 'SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
};

export const DirectoryTypes = {
  FETCH_DIRECTORY_START: 'FETCH_DIRECTORY_START',
  FETCH_DIRECTORY_SUCCESS: 'FETCH_DIRECTORY_SUCCESS',
  FETCH_DIRECTORY_FAILED: 'FETCH_DIRECTORY_FAILED',
};

export const CollectionTypes = {
  FETCH_COLLECTION_START: 'FETCH_COLLECTION_START',
  FETCH_COLLECTION_SUCCESS: 'FETCH_COLLECTION_SUCCESS',
  FETCH_COLLECTION_FAILED: 'FETCH_COLLECTION_FAILED',
};
